### ISSUE TITLE
github.com/hyperledger-labs/fabric-token-sdk: no Go source files

### ISSUE THREAD

**Issue by RongNK** [hyperledger-labs/fabric-token-sdk#133]
I am using Ubuntu 20.04 with 1.16 Go version.
I met this issue when execute this command "go get github.com/hyperledger-labs/fabric-smart-client"
Thank for your help!

**Comment by adecaro** [comment]
Hi @RongNK, I got rid of that part because it does not make sense anymore. Please have a look at the new [samples page](https://github.com/hyperledger-labs/fabric-token-sdk/blob/main/samples/README.md) to get examples on how to use the token-sdk :)
