### ISSUE TITLE
Token SDK: check well-formedness of inputs to token operations.

### ISSUE THREAD

**Issue by KElkhiyaoui** [hyperledger-labs/fabric-token-sdk#14]
Check that the token operations are called with valid arguments. 
**Examples:** 
- If an issuer calls issue with value "0" or type "", then token-sdk should return an error. 
- If a user calls transfer or redeem with value "0", then token-sdk should return an error.

**Comment by adecaro** [comment]
@KElkhiyaoui , can we close this?

**Comment by KElkhiyaoui** [comment]
yes - I will close it.
