### ISSUE TITLE
refactoring to make services backed agnostic

### ISSUE THREAD

**Issue by adecaro** [hyperledger-labs/fabric-token-sdk#205]
We now support both `fabric` and `orion` as backed to process the token transactions thanks to the `token/services/network` package that takes care of everything.

To better reflect that some services are not backend agnostic, this issue proposes the following refactoring:
- [x] rename `token/services/ttxcc` to `token/services/ttx` 
- [x] move `token/services/tcc` under `token/services/network/fabric`
- [x] rename `token/services/nftcc` to `token/serivces/nfttx`
- [x] move the content `integration/token/tcc` one level up, and remove `tcc`

**Comment by HagarMeir** [comment]
https://github.com/hyperledger-labs/fabric-token-sdk/pull/209

**Comment by adecaro** [comment]
done
