### ISSUE TITLE
ttxcc: automatic auditor selection

### ISSUE THREAD

**Issue by adecaro** [hyperledger-labs/fabric-token-sdk#22]
Currently, when auditing is enabled, the identity of the auditor must be passed at token transaction creation:
```
	tx, err := ttxcc.NewAnonymousTransaction(
		context,
		ttxcc.WithAuditor(fabric.GetIdentityProvider(context).Identity("auditor")),
	)
```
However, the public parameters supports a single auditor. 
Therefore, if the auditor is not explicitly passes at token transaction creation, it should be automatically set from the public parameters. If the identity of the auditor's FSC node cannot be resolved, then an error will be returned.

**Comment by adecaro** [comment]
does not apply anymore

**Comment by ntauth** [comment]
> does not apply anymore

How did this change? Is the auditor selected automatically without passing an identity to `NewAnonymousTransaction`?
