### ISSUE TITLE
Orion network service launched even no orion network config 

### ISSUE THREAD

**Issue by mffrench** [hyperledger-labs/fabric-token-sdk#250]
Hello,

as said by title we alway launch [orion network service](https://github.com/hyperledger-labs/fabric-token-sdk/blob/main/token/services/network/orion/driver.go#L33) even if useless. That's lead to some false error in the logs. 

That would be great to start orion network service if and only if a network is defined in conf. I guess we have potentially same topic to address with HLF ?

Best,

**Comment by adecaro** [comment]
what's the error log that you would like to not see?

**Comment by mffrench** [comment]
this one : https://github.com/mffrench/fabric-smart-client/commit/0dcd9f02d92b073addbffc6ff29f8498310a1454

**Comment by adecaro** [comment]
#635
