### ISSUE TITLE
unable to start Fabric network and the FSC network using ./nft network start --path ./testdata command

### ISSUE THREAD

**Issue by masool** [hyperledger-labs/fabric-token-sdk#274]
Hi there am using Go version is "go version go1.16.15 linux/amd64"
go build -o nft went successfull but trying to up and run FSC and fabric network getting below issue, Please help me to fix this issue.

2022-06-23 20:39:27.793 IST [nwo.network] Start -> INFO 001  ____    _____      _      ____    _____
2022-06-23 20:39:27.793 IST [nwo.network] Start -> INFO 002 / ___|  |_   _|    / \    |  _ \  |_   _|
2022-06-23 20:39:27.793 IST [nwo.network] Start -> INFO 003 \___ \    | |     / _ \   | |_) |   | |
2022-06-23 20:39:27.793 IST [nwo.network] Start -> INFO 004 ___) |    | |    / ___ \  |  _ <    | |
2022-06-23 20:39:27.793 IST [nwo.network] Start -> INFO 005 |____/    |_|   /_/   \_\ |_| \_\   |_|
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.

goroutine 1 [running]:
github.com/onsi/ginkgo.Fail(0xc0005a6040, 0x37, 0xc000c7f8d8, 0x1, 0x1)
	/home/masoolbabairfan/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:291 +0xc8
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/helpers.AssertImagesExist(0x25fd230, 0x1, 0x1)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/nwo/fabric/helpers/images.go:28 +0x38f
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric.NewPlatform(0x1ab1188, 0xc0005aa240, 0x1a7f6b8, 0xc0008b0200, 0x7f32870cd758, 0xc000684bc0, 0xc0003744d0)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/nwo/fabric/fabric.go:114 +0x57
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric.platformFactory.New(...)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/nwo/fabric/fabric.go:106
github.com/hyperledger-labs/fabric-smart-client/integration.(*Infrastructure).initNWO(0xc0005975c0)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/integration.go:298 +0x690
github.com/hyperledger-labs/fabric-smart-client/integration.(*Infrastructure).Generate(0xc0005975c0)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/integration.go:166 +0x35
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd/network.Start(0xc00056da10, 0x0, 0x0)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/nwo/cmd/network/cmd.go:187 +0x2b1
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd/network.StartCmd.func1(0xc0003a7080, 0xc0003a9ee0, 0x0, 0x2, 0x0, 0x0)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/nwo/cmd/network/cmd.go:151 +0x8c
github.com/spf13/cobra.(*Command).execute(0xc0003a7080, 0xc0003a9ec0, 0x2, 0x2, 0xc0003a7080, 0xc0003a9ec0)
	/home/masoolbabairfan/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a6000, 0x17a3571, 0xd, 0x0)
	/home/masoolbabairfan/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/masoolbabairfan/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd.(*Main).Execute(0xc00056d9e0)
	/home/masoolbabairfan/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220621081131-8a3f15b368c7/integration/nwo/cmd/main.go:56 +0x2dd
main.main()
	/src/github.com/hyperledger-labs/fabric-token-sdk/samples/nft/nft.go:42 +0x25d

**Comment by v13s** [comment]
Hey Masool,

Use a fresh Ubuntu 18.04 VM and execute the steps from below, let me know if you still face challenge.

#update libraries
```
sudo apt update
apt upgrade -y

```
#install make and build-essential
```
apt install make
apt-get install build-essential

```
#install go
```
wget -L https://go.dev/dl/go1.17.11.linux-amd64.tar.gz
tar -xvf go1.17.11.linux-amd64.tar.gz
sudo chown -R root:root ./go
sudo mv -v go /usr/local

vim ~/.bash_profile
source ~/.bash_profile

echo $GOPATH
echo $GOROOT
go version
```
#install docker
```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg  | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
sudo apt-get update
apt-cache policy docker-ce
sudo apt-get install -y docker-ce  --assume-yes
docker version
```
#install docker-compose
```
DOCKER_COMPOSE_VERSION=${1:-1.26.2}
sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)"
sudo chmod +x /usr/local/bin/docker-compose
docker-compose -v
sudo usermod -aG docker $USER
```
#setup fabric-token-sdk
```
export FTS_PATH=$GOPATH/src/github.com/hyperledger-labs/fabric-token-sdk
git clone https://github.com/hyperledger-labs/fabric-token-sdk.git $FTS_PATH
cd $GOPATH/src/github.com/hyperledger-labs/fabric-token-sdk
make docker-images
```
#working with nft in samples for fabric-token-sdk
```
cd samples/nft/
go build -o nft
```
#start your sample on screen
```
screen
./nft network start --path ./testdata
```

Please note the same has been copied from https://cogniverse.net/how-to-setup-test-nft-sample-using-fabric-token-sdk/

**Comment by adecaro** [comment]
Thanks a lot @v13s for your support.

@masool , I'll close this issue. Feel free to reopen it if you still have issues. Thanks :)
