### ISSUE TITLE
RegisterResponder function needs to have AcceptCashView{} and IssueCashView{}

### ISSUE THREAD

**Issue by NorhanKhaled** [hyperledger-labs/fabric-token-sdk#276]
if I have 2 applications 1 is for the issuer which will issue tokens and one is for the recipient that will accept tokens , in that case I should not have the issue cash view on the recipient node side
how will I configure the registerResponder ? and the same for transfer view

**Comment by adecaro** [comment]
This is an FSC issue, right?
