### ISSUE TITLE
Is there a clear version for the stack figure?

### ISSUE THREAD

**Issue by yeasy** [hyperledger-labs/fabric-token-sdk#28]
The link is https://raw.githubusercontent.com/hyperledger-labs/fabric-token-sdk/main/docs/imgs/stack.png, which is difficult to read the words on it.
Thanks!

**Comment by adecaro** [comment]
Aha, thanks for pointing out. I will post a clearer picture.

**Comment by adecaro** [comment]
What about now? :)

**Comment by yeasy** [comment]
Much better, thanks!
