### ISSUE TITLE
Allow the auditor to access idemix credential's revocation handle

### ISSUE THREAD

**Issue by KElkhiyaoui** [hyperledger-labs/fabric-token-sdk#295]
Currently, the auditor receives only the opening of the Enrolment ID. This issue asks to add attach to the Idemix credential also a commitment to the revocation handle and pass the opening to the auditor in such a way the auditor can verify that the revocation handle is correct.

This will require changes to github.com/IBM/idemix, fabric-smart client, and to the token-sdk.

Related Idemix Issue: https://github.com/IBM/idemix/issues/21

**Comment by adecaro** [comment]
done
