### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adecaro** [hyperledger-labs/fabric-token-sdk#3]
Documentation should about 
- [ ] concise feature list
- [ ] Architecture
- [ ] Tutorial: Write your first Token-Based Distributed Application
- [ ] Advanced deployment
- [ ] Integration Tests

**Comment by rajat-dlt** [comment]
Any plans of picking this task in the near future? 
Especially the "Tutorial: Write your first Token-Based Distributed Application".
