### ISSUE TITLE
Enable staticcheck in CI

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-token-sdk#317]
An assessment of the current code is needed and staticchecks issues should be resolved before enabling staticcheck in CI.

**Comment by alexandrosfilios** [comment]
Checks to be addressed:

- [ ] ST1001 https://github.com/hyperledger-labs/fabric-token-sdk/pull/323
- [ ] S1023 https://github.com/hyperledger-labs/fabric-token-sdk/pull/324
- [ ] S1011 https://github.com/hyperledger-labs/fabric-token-sdk/pull/326
- [ ] S1039 https://github.com/hyperledger-labs/fabric-token-sdk/pull/327
- [ ] SA4010 https://github.com/hyperledger-labs/fabric-token-sdk/pull/328
- [ ] SA9003 https://github.com/hyperledger-labs/fabric-token-sdk/pull/329
- [ ] S1038, S1012, S1021, SA4001 PR to open
- [ ] SA5007 PR to open
- [ ] SA1019 PR to open
- [ ] SA4022
- [ ] SA4011
- [ ] U1000
