### ISSUE TITLE
Any plan to follow ERC20 or the Hyperledger Token Taxonomy Framework?

### ISSUE THREAD

**Issue by yeasy** [hyperledger-labs/fabric-token-sdk#32]
This may help improve the inter-operability.

**Comment by adecaro** [comment]
Hi @yeasy, this is a very interesting point. What about moving it to [`Discussion`](https://github.com/hyperledger-labs/fabric-token-sdk/discussions) to have a more lengthy interaction? :)

**Comment by yeasy** [comment]
Moved to https://github.com/hyperledger-labs/fabric-token-sdk/discussions/38.
