### ISSUE TITLE
Support PKCS11

### ISSUE THREAD

**Issue by Timo-1** [hyperledger-labs/fabric-token-sdk#320]
Currently, FTS code often directly uses the Go crypto package, e.g. create and use ecdsa keys in `token/core/zkatdlog/crypto/ecdsa/ecdsa.go` and `token/core/identity/msp/x509/ecdsa.go` etc.

Instead, FTS should use the fabric BCCSP providers, including the BCCSP PKCS11 provider.

Goal is to enable FTS to use HSMs.

Similar issue for FSC: https://github.com/hyperledger-labs/fabric-smart-client/issues/281

**Comment by adecaro** [comment]
Hi @Timo-1, this is a very good point.

Indeed, we can already leverage the HSM for two very critical class of keys: The issuer and the auditor keys.

It should be easy to get this support using Fabric support as you suggested :)

**Comment by Timo-1** [comment]
Hi @adecaro 
Thank you very much for implementing this feature. It works greatly, and I now can use FTS with a HSM for the issuer and auditor keys.

**Comment by adecaro** [comment]
@Timo-1 fantastic :)
