### ISSUE TITLE
auditTransactions returns values even if there is no transactions for recipient

### ISSUE THREAD

**Issue by NorhanKhaled** [hyperledger-labs/fabric-token-sdk#322]
I tried to make transactions for Bob and Alice , however when I executed auditedTransactionView for Charlie , I expected that will be no transactions 
however I retrieved values 
{"TxID":"c4ec7394c486340aab7a725acd8857592a0f05856fde0a460eeb7cb25bdef226","ActionType":0,"SenderEID":"","RecipientEID":"alice","TokenType":"USD","Amount":110,"Timestamp":"2022-08-02T15:19:52.185203+02:00","Status":"Confirmed"},{"TxID":"88a7120545c491116e095780661f1b1edcaa2628a6b3b39c108ebf11ebaddead","ActionType":0,"SenderEID":"","RecipientEID":"alice","TokenType":"USD","Amount":10,"Timestamp":"2022-08-02T15:19:54.63133+02:00","Status":"Confirmed"}

**Comment by adecaro** [comment]
Hi @NorhanKhaled , what's the status of this? Did we get an agreement?
