### ISSUE TITLE
FTS fungible samples inconsistency

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-token-sdk#350]
The code blocks in the README.md of the fungible samples seems to be inconsistent as reported by @mbwhite.

We need to check this and make sure that they are the same.

Questions: 
- Can we include go code in markdown? 
- Or can we generate markdown?
- How can we automate this?

These questions are also relevant for the Fabric Smart Client and related to the issue https://github.com/hyperledger-labs/fabric-smart-client/issues/263

**Comment by adecaro** [comment]
samples have been removed
