### ISSUE TITLE
Swap view - asserting transaction output fails

### ISSUE THREAD

**Issue by IgorSimj** [hyperledger-labs/fabric-token-sdk#459]
For example, Alice have 10 TOK and Bob have 5 KOT

Swap view is initiated (from Alice's node), 1 TOK for 1 KOT. 
After Bob add his own transfers execution continue at Alice's node where tx outputs will be checked.
```

outputs, err := tx.Outputs()
os := outputs.ByRecipient(other)
assert.Equal(0, os.Sum().Cmp(big.NewInt(int64(t.FromQuantity))))
```
'os' object contain Bob's outputs (1 TOK, 4 KOT) and assert will fail. 
Here, we need to analyze action by action.

**Comment by adecaro** [comment]
done
