### ISSUE TITLE
Get Balances of All the controlled wallets

### ISSUE THREAD

**Issue by Sahith-Shetty** [hyperledger-labs/fabric-token-sdk#462]
a function to retrieve balances of all the wallets from fsc node wallet manager

**Comment by adecaro** [comment]
Hi @Sahith-Shetty , I think we can close this. It is now available an API to get the ids of all owner wallets. See `WalletManager@OwnerWalletIDs`. What do you think?

**Comment by Sahith-Shetty** [comment]
yes @adecaro, should be good enough. Thanks
