### ISSUE TITLE
Dependency on fabric 1.4

### ISSUE THREAD

**Issue by corthDfine** [hyperledger-labs/fabric-token-sdk#552]
Hi all,

I saw that from go.mod that the sdk is depending on the following fabric version

github.com/hyperledger/fabric v1.4.0-rc1.0.20230405174026-695dd57e01c2

is there any plan to upgrade that dependency to a more recent release?
And if so, what is the approximate timeline for that?

Thanks

**Comment by adecaro** [comment]
Hi @corthDfine , 

Unfortunately, Fabric did not handle properly the mod versioning at the time of introduction of that feature into golang.
So, every time we import Fabric we get that strange encoding.

What is relevant is the commit number `695dd57e01c2`. This should correspond to Fabric 2.5.

Hope this helps.

**Comment by corthDfine** [comment]
Thanks a lot for the insight.
