### ISSUE TITLE
Validate what we sign in the endorser view

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/fabric-token-sdk#62]
In **token/services/ttxcc/endorse.go**, the **endorseView**'s **Call()** method blindly signs anything but does not validate what it signs

**Comment by adecaro** [comment]
@yacovm , this is the expected behaviour because any check should be done before that view is invoked. Look here, for example [`here`](https://github.com/hyperledger-labs/fabric-token-sdk/blob/main/integration/token/tcc/basic/views/accept.go)
