### ISSUE TITLE
create a docker image for token chaincode (tcc)

### ISSUE THREAD

**Issue by mffrench** [hyperledger-labs/fabric-token-sdk#93]
Hello,

we're using zkatcc as an external chaincode on HLF. As such we're building by ourself the zkat chaincode docker image but I think this project should be the proper location for such build.

For such task, we would need a docker image repository. As Fabric Token SDK is now open source,  I suggest to use the official docker hub. Then we should think on the delivery pipeline for such chaincode delivery : 

- how do we manage latest image update ? 
- how do we manage tagged image publication ?
- ...

Also, on our current zkat chaincode, we embedd the tokengen tool that way we just need the zkat chaincode image to use that tool and we do not need to build it on each of our developpers env. This choice may be discussed and may be we would prefer other way to deliver such tool : 

- a dedicated docker image for fts toolings ? 
- a binary delivery for any platform (linux, osx ...) ? 
- ... ?

**Comment by adecaro** [comment]
will address when time comes
